### PR TITLE
add missing include

### PR DESCRIPTION
**Pull request by tcriess**
Make it compile on current Ubuntu gcc.

### CODE REVIEW

**Comment by arnaud-carre** [comment]
would #include <string.h> also work? (it would be more in phase with other .cpp )

**Comment by tcriess** [comment]
just tried it - yes, string.h is also fine. thanks for your work - for me, that is actually a game-changer for the 4kb intro :)

**Comment by arnaud-carre** [comment]
ok so I pushed a fix with some warnings fixed also. It should be good now
for gcc. Thanks for noticing!

**Comment by tcriess** [comment]
perfect, thank you!

**Pull request closed without merging**
